# **Numpy Basic Functions**

### What is numpy?

NumPy is a basic and important Python library for scientific computing. It provides a multidimensional array that allows us to store and work with large amounts of data easily. It also provides many functions for mathematical calculations, logical operations, changing the shape of data, sorting, selecting data, statistics, linear algebra, random numbers, and more.

The main object in NumPy is called ndarray. It is used to store one-dimensional, two-dimensional, or multi-dimensional arrays. The elements in a NumPy array generally have the same data type

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size when they are created, while Python lists can grow or shrink easily. If the size of a NumPy array needs to be changed, a new array is generally created.

- The elements of a NumPy array are usually of the same data type, so they take the same amount of memory. Python lists can contain different types of data.

- NumPy arrays are designed for fast mathematical and numerical operations on large amounts of data. These operations are usually faster and require less code compared to using normal Python lists.

- NumPy is also widely used by other scientific, Data Science, and Machine Learning libraries. These libraries often convert Python lists or other sequences into NumPy arrays before processing the data and may also return NumPy arrays as the result.

In [2]:
import numpy as np
a=np.array([4,4,5,9,6])
print(a)

[4 4 5 9 6]


In [5]:
np.array([[4,6],[5,9],[4,7],[9,3]])

array([[4, 6],
       [5, 9],
       [4, 7],
       [9, 3]])

In [6]:
np.array([4,6,7],dtype=float)

array([4., 6., 7.])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.ones((3,2)) # Used for initilization of array.It is generally used in Deep Learning for neural network

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.random.random((3,3)) # It give numbers from 0 to 1

array([[0.33217167, 0.7012746 , 0.75821501],
       [0.68087981, 0.26698982, 0.25434866],
       [0.44970685, 0.47261157, 0.87313138]])

In [28]:
np.linspace(-5,5,7,dtype=int)# it give numbers at equal distance
np.linspace(-5,5,7)
# 1st num = lower range
# 2nd num = upper range
# 3rd num =  No. of items

array([-5.        , -3.33333333, -1.66666667,  0.        ,  1.66666667,
        3.33333333,  5.        ])

In [25]:
np.identity(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Numpy Attributes**

In [49]:
m1=np.arange(10)
m2=np.arange(12,dtype=float).reshape(3,4)
m3=np.arange(8).reshape(2,2,2)
m3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
m2.ndim # for Dimention 2D-  is the collection 1D array

2

In [45]:
m3.shape  # in this shape 1st num=no. of 1D array
          # 2nd num=2 rows    3rd num=2col  

(2, 2, 2)

In [46]:
m2.itemsize         # int32 has 4 bits size
                    # in64 (default) has 8 size == float(8)
# Every item how much space occupy in memory- itemsize

8

In [47]:
#dtype
print(m1.dtype)
print(m2.dtype)
print(m3.dtype)

int64
float64
int64


# **Changing Datatype**

In [52]:
# astype
m3.astype(np.int32) # Used for Memory space management

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# **Array Operations**

In [55]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [58]:
# scalar operation(Operation with scalar)
a1*4  # Every operwator works here(+,-,*,**,/)

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [59]:
# Relatinal
a1==5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [60]:
# vector operation
a1+a2  # operation on 2 numpy array

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# **Array Functions**

In [64]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[ 72., 100.,  22.],
       [ 82.,  49.,  18.],
       [  3.,  90.,   6.]])

In [67]:
#0-column 1-row
print(np.max(a1,axis=0))
print(np.min(a1,axis=1))
print(np.sum(a1))
print(np.prod(a1))

[ 82. 100.  22.]
[22. 18.  3.]
442.0
18558916992000.0


In [68]:
print(np.mean(a1,axis=0))
print(np.median(a1,axis=1))
print(np.std(a1))
print(np.var(a1))

[52.33333333 79.66666667 15.33333333]
[72. 49.  6.]
35.831223021407965
1283.8765432098762


In [4]:
# dot product(Multiplication of matrix)
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [5]:
np.log(a2)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [6]:
k=np.log(a2)

In [83]:
np.exp(a2)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [84]:
np.round(k*100)

array([[248., 256., 264.],
       [271., 277., 283.],
       [289., 294., 300.],
       [304., 309., 314.]])

In [9]:
import numpy as np
np.floor(k)


array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [86]:
np.ceil(k)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [4., 4., 4.]])

# **Indexing and Slicing**

## 1) Indexing

In [4]:
m1=np.arange(10)
m2=np.arange(12,dtype=float).reshape(3,4)
m3=np.arange(8).reshape(2,2,2)

In [88]:
print(m1)
m1[-1]

[0 1 2 3 4 5 6 7 8 9]


np.int64(9)

In [89]:
m2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [92]:
print(m2[1,1])

5.0


In [93]:
m3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
print(m3[1,0,1])    # 1st num = which matrix?
#2nd num  = which row?
# 3rd num = which col?
m3[0,1,1]

5


np.int64(3)

## 2) Slicing

In [96]:
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
print(m1[2:5:2])

[2 4]


In [99]:
m2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [7]:
print(m2[0,:])
print(m2[1,::3])
print(m2[::2,0])
print(m2[1:,2:])
print(m2[:,1:])
print(m2[::2,::3])
print(m2[::2,::2])

[0. 1. 2. 3.]
[4. 7.]
[0. 8.]
[[ 6.  7.]
 [10. 11.]]
[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 9. 10. 11.]]
[[ 0.  3.]
 [ 8. 11.]]
[[ 0.  2.]
 [ 8. 10.]]


In [12]:
m3=np.arange(27).reshape(3,3,3)
m3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
print(m3[1])  # For 1st matrix 
print(m3[1,:,1])  # for 2nd matrix 2 column
print(m3[2,1:,1:]) # for 3rd matrix bottom right 2x2 matrix 
print(m3[::2,0,::2]) 

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


# Iterating

In [117]:
m1
for i in m1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [120]:
m2
for i in m2:
    print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [121]:
m3
for i in  m3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [123]:
for i in np.nditer(m3): # np.nditer convert nD aray to 1D array and print(i)
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [126]:
np.transpose(m2) 
# or
m2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [131]:
m2  # any kind of matrix converts into 1D array
m2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

# Stacking
Same shape is required

In [3]:
# Horizontal
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
np.hstack((a4,a5))   # Joints two matrix horizontaly

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [5]:
np.vstack((a4,a5))   # Joints two matrix verticaly

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [6]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.hsplit(a4,2)  # splits vertically but in equal parts

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [11]:
np.vsplit(a4,3)   # splits horizontally but in equal parts

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]