# **Numpy Question**
**Note: First of all try Yourself then Google it for most Efficient Answer**

In [1]:
import numpy as np
np.random.seed(42)

###`Q-1` Create a null vector of size 12 but the eighth value which is 5.

In [2]:
#Code here
a = np.zeros(12)
# 8th value means index 7, because index starts from 0
a[7] = 5
a

array([0., 0., 0., 0., 0., 0., 0., 5., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers r, c. Write a program to generate a random array of shape (r, c) and print the array, max, min and avg of the array.

In [3]:
#Code here
# r = int(input("Enter rows:"))
# c = int(input("Enter columns:"))
r, c = 3, 4
# rand gives random numbers between 0 and 1
arr = np.random.rand(r, c)
print(arr)
print('Max:', round(arr.max(), 2))
print('Min:', round(arr.min(), 2))
print('Average:', round(arr.mean(), 2))

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
Max: 0.97
Min: 0.02
Average: 0.52


###`Q-3` Write a function to create a 2d array with 0 on the border and 1 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[0,0,0,0,0],
[0,1,1,1,0],
[0,1,1,1,0],
[0,0,0,0,0]]
```

In [4]:
#Code here
def border_zero(a, b):
    arr = np.zeros((a, b), dtype=int)
    # first make everything 0, then put 1 inside (leave first and last row and column)
    arr[1:a-1, 1:b-1] = 1
    return arr

border_zero(4, 5)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

###`Q-4` Create a vector of size 8 with random values between 5 and 10, both excluded.

In [5]:
#Code here
# uniform gives random numbers between 5 and 10
v = np.random.uniform(5, 10, 8)
v

array([9.1622132 , 6.06169555, 5.90912484, 5.91702255, 6.52121121,
       7.62378216, 7.15972509, 6.4561457 ])

###`Q-5` Can you create a matrix of shape (4,3) with 1 on the main diagonal and 0 everywhere else? If yes write code for it.

In [6]:
#Code here
# yes, np.eye works for any shape, but np.identity works only for square shape
np.eye(4, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

###`Q-6:` Create a 6x6 matrix with row values ranging from 0 to 5. Then create another 6x6 matrix where row i is filled with the value i.

In [7]:
#Code here
# repeat [0 1 2 3 4 5] six times in rows
np.tile(np.arange(6), (6, 1))

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [8]:
# first make it a column with reshape, then repeat it six times in columns
np.tile(np.arange(6).reshape(-1, 1), (1, 6))

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5]])

###`Q-7:` Consider a random integer (in range 1 to 20) array with shape `(6,2)` representing coordinates (x,y), and coordinates of a point as array is given. Create an array of distance of each point in the random array from the given point. Distance array should be integer type.

In [9]:
point = np.array([2, 3])

In [10]:
#Code here
pts = np.random.randint(1, 20, (6, 2))
# subtract the point from every row, square it, add each row and take root
# astype(int) is for making it integer
dist = np.sqrt(((pts - point) ** 2).sum(axis=1)).astype(int)
print(pts)
print(dist)

[[10 16]
 [15 15]
 [19 12]
 [ 3  5]
 [19  7]
 [ 9  7]]
[15 17 19  2 17  8]


###`Q-8:` Create a (4,5) shape array with numbers from 1 to 20. What is the index (row, column) of the number 12?

In [11]:
#Code here
a = np.arange(1, 21).reshape(4, 5)
print(a)
# a == 12 is True only at the place of 12, np.where gives the index of it
np.where(a == 12)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


(array([2]), array([1]))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type int.

**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type int.

**Example 1:**

Input:

```bash
1.5 2.7 3 -4.9 8
```

Output:

```bash
[ 8 -4  3  2  1]
```

In [12]:
#Code here
def reverse_int(s):
    # split the numbers, make float array, reverse it with [::-1], then change to int
    arr = np.array(s.split(), dtype=float)
    return arr[::-1].astype(int)

# s = input()
reverse_int("1.5 2.7 3 -4.9 8")

array([ 8, -4,  3,  2,  1])

### `Q-10:` Array details

For a given numpy array print the number of elements, dimensions, shape and the count of non zero elements.

**Example 1:**

Input:
```bash
np.array([[1, 0, 3], [0, 5, 6]])
```

Output:
```bash
elements :  6
ndim :  2
shape :  (2, 3)
non zero :  4
```

In [13]:
#Code here
# size is total elements, count_nonzero counts the numbers which are not 0
def details(arr):
    print("elements : ", arr.size)
    print("ndim : ", arr.ndim)
    print("shape : ", arr.shape)
    print("non zero : ", np.count_nonzero(arr))

details(np.array([[1, 0, 3], [0, 5, 6]]))

elements :  6
ndim :  2
shape :  (2, 3)
non zero :  4


### `Q-11:` Min-Max scaling

Create a Python function to apply Min-Max scaling on the given numpy array. The function only accepts a numpy array, otherwise raise error.

$$\Large x'_i = \frac{x_i - min(x)}{max(x) - min(x)}$$

**Example 1:**

Input:
```bash
[10 20 30 40 50]
```

Output:
```bash
[0.   0.25 0.5  0.75 1.  ]
```

**Example 2:**

Input:
```bash
[3 9 6]
```

Output:
```bash
[0.  1.  0.5]
```

In [14]:
#Code here
def min_max(arr):
    # if it is not a numpy array then raise error
    if type(arr) != np.ndarray:
        raise TypeError("only numpy array allowed")
    return (arr - arr.min()) / (arr.max() - arr.min())

print(min_max(np.array([10, 20, 30, 40, 50])))
print(min_max(np.array([3, 9, 6])))

[0.   0.25 0.5  0.75 1.  ]
[0.  1.  0.5]


### `Q-12:` Stack arrays

Write a python function that accepts two numpy arrays of shape (2,2) and returns both, stacked vertically and stacked horizontally. The function only accepts numpy arrays, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[1 2]
 [3 4]]

b= [[5 6]
 [7 8]]
```

Output:

```bash
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]
```

In [15]:
#Code here
def stack_both(a, b):
    if type(a) != np.ndarray or type(b) != np.ndarray:
        raise TypeError("only numpy arrays allowed")
    # vstack joins one below another, hstack joins side by side
    return np.vstack((a, b)), np.hstack((a, b))

v, h = stack_both(np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]))
print(v)
print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### `Q-13:` Dates

Create an array of all the dates of March 2024 and print how many dates are there in it. Also print the first 5 dates only.

**Output:**
```bash
31
['2024-03-01' '2024-03-02' '2024-03-03' '2024-03-04' '2024-03-05']
```

In [16]:
#Code here
# this gives one date for every day, the end date (1 April) is not included
dates = np.arange('2024-03-01', '2024-04-01', dtype='datetime64[D]')
print(len(dates))
print(dates[:5])

31
['2024-03-01' '2024-03-02' '2024-03-03' '2024-03-04' '2024-03-05']


###`Q-14:` Subtract the mean of each row from a matrix.

Hint: use keepdims=True so that the shape of the mean array stays 2D.

In [17]:
#Code here
m = np.arange(12).reshape(4, 3)
# axis=1 means mean of each row, keepdims=True keeps it 2D so the subtraction works
result = m - np.mean(m, axis=1, keepdims=True)
print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap row-1 of array with row-3 in the array.

In [18]:
#Code here
mat = np.arange(12).reshape(4, 3)
# take row 0 and row 2 and put them in reverse order
mat[[0, 2]] = mat[[2, 0]]
mat

array([[ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11]])

###`Q-16:` Replace all the odd numbers in `np.arange(1, 13)` with -1 without changing the original array.

In [19]:
#Code here
a = np.arange(1, 13)
# where the number is odd put -1, otherwise keep the same number
b = np.where(a % 2 == 1, -1, a)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12]


###`Q-17:` Sort each row of the given 2D array in increasing order.

In [20]:
#Code here
data = np.array([[9, 1, 5],
                 [8, 3, 2],
                 [7, 6, 4]])
# axis=1 means sort inside each row
np.sort(data, axis=1)

array([[1, 5, 9],
       [2, 3, 8],
       [4, 6, 7]])

###`Q-18:` Find the unique elements of the array `[3, 1, 3, 2, 3, 1, 2, 2, 2]` and also count how many times 2 came.

In [21]:
#Code here
arr = np.array([3, 1, 3, 2, 3, 1, 2, 2, 2])
# unique gives the different numbers, (arr == 2).sum() counts the True values
print(np.unique(arr))
print((arr == 2).sum())

[1 2 3]
4
